dataset: "karate"
train_comm_det_alg: greedy

karate:
  evader:
    T: 50
    u: 10
    lambd: 1
    lr: 0.01
    budget: 10
    tau: 0.5
    attention: True
    reinitialization: True

words:
  evader:
    T: 100
    u: 10
    lambd: 1
    lr: 0.01
    dist_f: frobenius_dist
    budget_factor: 1
    tau: 0.5
    attention: True
    reinitialization: True

vote:
  evader:
    T: 100
    u: 10
    lambd: 10
    lr: 0.005
    dist_f: frobenius_dist
    budget_factor: 1
    tau: 0.5
    attention: True
    reinitialization: True

