dataset: kar
train_alg: greedy
test_alg: greedy
seed: 22
attention: True
reinitialization: True
dist_f: frobenius_dist
u: 0
tau: 0.5
beta: 1
attention_coeffs: [0.333, 0.333, 0.167, 0.167]

kar:
  testing_greedy:
    tau_0.5:
      beta_0.5:
          T: 100
          lr : 0.082
          lambd: 0.32
      beta_1:
          T: 100
          lr : 0.11
          lambd: 0.178
      beta_2:
          T: 90
          lr : 0.061
          lambd: 1.18
  testing_louvain:
    tau_0.5:
      beta_0.5:
          T: 30
          lr : 0.165
          lambd: 0.64
      beta_1:
          T: 70
          lr : 0.17
          lambd: 0.82
      beta_2:
          T: 70
          lr : 0.14
          lambd: 0.03
  testing_walktrap:
    tau_0.5:
      beta_0.5:
          T: 90
          lr : 0.075
          lambd: 1.97
      beta_1:
          T: 100
          lr : 0.186
          lambd: 0.94
      beta_2:
          T: 100
          lr : 0.248
          lambd: 1.95

words:
  testing_greedy:
    tau_0.5:
      beta_0.5:
          T: 100
          lr : 0.068
          lambd: 1.86
      beta_1:
          T: 80
          lr : 0.028
          lambd: 1.59
      beta_2:
          T: 60
          lr : 0.035
          lambd: 1.99
  testing_louvain:
    tau_0.5:
      beta_0.5:
          T: 80
          lr : 0.073
          lambd: 0.098
      beta_1:
          T: 50
          lr : 0.046
          lambd: 1.65
      beta_2:
          T: 30
          lr : 0.134
          lambd: 0.69
  testing_walktrap:
    tau_0.5:
      beta_0.5:
          T: 70
          lr : 0.058
          lambd: 0.397
      beta_1:
          T: 80
          lr : 0.0799
          lambd: 0.09
      beta_2:
          T: 60
          lr : 0.12
          lambd: 0.15

vote:
  testing_greedy:
    tau_0.5:
      beta_0.5:
          T: 190
          lr : 0.009
          lambd: 9.93
      beta_1:
          T: 170
          lr : 0.0099
          lambd: 9.83
      beta_2:
          T: 180
          lr : 0.0058
          lambd: 9.78
  testing_louvain:
    tau_0.5:
      beta_0.5:
          T: 60
          lr : 0.0081
          lambd: 6.11
      beta_1:
          T: 40
          lr : 0.0088
          lambd: 8.50
      beta_2:
          T: 130
          lr : 0.056
          lambd: 7.27
  testing_walktrap:
    tau_0.5:
      beta_0.5:
          T: 190
          lr : 0.0033
          lambd: 0.26
      beta_1:
          T: 140
          lr : 0.055
          lambd: 4.9
      beta_2:
          T: 100
          lr : 0.058
          lambd: 5.57


pow:
  testing_greedy:
    tau_0.5:
      beta_0.5:
          T: 120
          lr : 0.0063
          lambd: 21
      beta_1:
          T: 200
          lr : 0.0072
          lambd: 18.5
      beta_2:
          T: 260
          lr : 0.0083
          lambd: 0.39
  testing_louvain:
    tau_0.5:
      beta_0.5:
          T: 270
          lr : 0.0038
          lambd: 8.97
      beta_1:
          T: 210
          lr : 0.0014
          lambd: 5.26
      beta_2:
          T: 240
          lr : 0.0055
          lambd: 2.29
  testing_walktrap:
    tau_0.5:
      beta_0.5:
          T: 280
          lr : 0.0064
          lambd: 29.26
      beta_1:
          T: 300
          lr : 0.0074
          lambd: 26.84
      beta_2:
          T: 220
          lr : 0.0066
          lambd: 36.8

fb:
  testing_greedy:
    tau_0.5:
      beta_0.5:
          T: 290
          lr : 0.0011
          lambd: 4.97
      beta_1:
          T: 250
          lr : 0.008
          lambd: 26
      beta_2:
          T: 290
          lr : 0.0098
          lambd: 0.23
  testing_louvain:
    tau_0.5:
      beta_0.5:
          T: 150
          lr : 0.0058
          lambd: 72.89
      beta_1:
          T: 120
          lr : 0.0093
          lambd: 0.93
      beta_2:
          T: 170
          lr : 0.0011
          lambd: 21.3
  testing_walktrap:
    tau_0.5:
      beta_0.5:
          T: 70
          lr : 0.0053
          lambd: 1.96
      beta_1:
          T: 190
          lr : 0.0026
          lambd: 4.2
      beta_2:
          T: 140
          lr : 0.001
          lambd: 6.7

