dataset: karate
train_alg: greedy
test_alg: greedy

attention: True
reinitialization: True
dist_f: frobenius_dist
u: 0
tau: 0.5
budget_factor: 1

kar:
  training_greedy:
    testing_greedy:
      tau_0.5:
        beta_0.5:
            T: 60
            lr : 0.0982
            lambd: 0.798
        beta_1:
            T: 100
            lr : 0.22
            lambd: 1.73
        beta_2:
            T: 100
            lr : 0.237
            lambd: 3.436
    testing_louvain:
      tau_0.5:
        beta_0.5:
            T: 100
            lr : 0.094
            lambd: 1.155
        beta_1:
            T: 80
            lr : 0.4
            lambd: 4.8
        beta_2:
            T: 80
            lr : 0.388
            lambd: 1.854
    testing_walktrap:
      tau_0.5:
        beta_0.5:
            T: 70
            lr : 0.17
            lambd: 0.699
        beta_1:
            T: 60
            lr : 0.3
            lambd: 3.77
        beta_2:
            T: 100
            lr : 0.479
            lambd: 4.429

words:
  training_greedy:
    testing_greedy:
      tau_0.5:
        beta_0.5:
            T: 80
            lr : 0.032
            lambd: 3.6
        beta_1:
            T: 80
            lr : 0.041
            lambd: 1.49
        beta_2:
            T: 90
            lr : 0.059
            lambd: 4.99
    testing_louvain:
      tau_0.5:
        beta_0.5:
            T: 70
            lr : 0.3
            lambd: 0.756
        beta_1:
            T: 50
            lr : 0.1
            lambd: 0.65
        beta_2:
            T: 80
            lr : 0.127
            lambd: 3.38
    testing_walktrap:
      tau_0.5:
        beta_0.5:
            T: 80
            lr : 0.059
            lambd: 4.615
        beta_1:
            T: 80
            lr : 0.096
            lambd: 0.344
        beta_2:
            T: 90
            lr : 0.154
            lambd: 0.8

vote:
  training_greedy:
    testing_greedy:
      tau_0.5:
        beta_0.5:
            T: 190
            lr : 0.009
            lambd: 9.93
        beta_1:
            T: 170
            lr : 0.0099
            lambd: 9.83
        beta_2:
            T: 180
            lr : 0.0058
            lambd: 9.78
    testing_louvain:
      tau_0.5:
        beta_0.5:
            T: 60
            lr : 0.0081
            lambd: 6.11
        beta_1:
            T: 40
            lr : 0.0088
            lambd: 8.50
        beta_2:
            T: 130
            lr : 0.056
            lambd: 7.27
    testing_walktrap:
      tau_0.5:
        beta_0.5:
            T: 190
            lr : 0.0033
            lambd: 0.26
        beta_1:
            T: 140
            lr : 0.055
            lambd: 4.9
        beta_2:
            T: 100
            lr : 0.058
            lambd: 5.57


pow:
  training_greedy:
    testing_greedy:
      tau_0.5:
        beta_0.5:
            T: 120
            lr : 0.0063
            lambd: 21
        beta_1:
            T: 200
            lr : 0.0072
            lambd: 18.5
        beta_2:
            T: 260
            lr : 0.0083
            lambd: 0.39
    testing_louvain:
      tau_0.5:
        beta_0.5:
            T: 270
            lr : 0.0038
            lambd: 8.97
        beta_1:
            T: 210
            lr : 0.0014
            lambd: 5.26
        beta_2:
            T: 240
            lr : 0.0055
            lambd: 2.29
    testing_walktrap:
      tau_0.5:
        beta_0.5:
            T: 280
            lr : 0.0064
            lambd: 29.26
        beta_1:
            T: 300
            lr : 0.0074
            lambd: 26.84
        beta_2:
            T: 220
            lr : 0.0066
            lambd: 36.8

fb:
  training_greedy:
    testing_greedy:
      tau_0.5:
        beta_0.5:
            T: 290
            lr : 0.0011
            lambd: 4.97
        beta_1:
            T: 250
            lr : 0.008
            lambd: 26
        beta_2:
            T: 290
            lr : 0.0098
            lambd: 0.23
    testing_louvain:
      tau_0.5:
        beta_0.5:
            T: 150
            lr : 0.0058
            lambd: 72.89
        beta_1:
            T: 120
            lr : 0.0093
            lambd: 0.93
        beta_2:
            T: 170
            lr : 0.0011
            lambd: 21.3
    testing_walktrap:
      tau_0.5:
        beta_0.5:
            T: 70
            lr : 0.0053
            lambd: 1.96
        beta_1:
            T: 190
            lr : 0.0026
            lambd: 4.2
        beta_2:
            T: 140
            lr : 0.001
            lambd: 6.7

