dataset: karate
train_alg: greedy
test_alg: greedy

attention: True
reinitialization: True
dist_f: frobenius_dist
u: 0
tau: 0.5
budget_factor: 1

karate:
  training_greedy:
    testing_greedy:
      tau_0.5:
        beta_0.5:
            T: 100
            lr : 0.082
            lambd: 0.32
        beta_1:
            T: 100
            lr : 0.11
            lambd: 0.178
        beta_2:
            T: 90
            lr : 0.061
            lambd: 1.18
    testing_louvain:
      tau_0.5:
        beta_0.5:
            T: 30
            lr : 0.165
            lambd: 0.64
        beta_1:
            T: 70
            lr : 0.17
            lambd: 0.82
        beta_2:
            T: 70
            lr : 0.14
            lambd: 0.03
    testing_walktrap:
      tau_0.5:
        beta_0.5:
            T: 90
            lr : 0.075
            lambd: 1.97
        beta_1:
            T: 100
            lr : 0.186
            lambd: 0.94
        beta_2:
            T: 100
            lr : 0.248
            lambd: 1.95

words:
  training_greedy:
    testing_greedy:
      tau_0.5:
        beta_0.5:
            T: 100
            lr : 0.068
            lambd: 1.86
        beta_1:
            T: 80
            lr : 0.028
            lambd: 1.59
        beta_2:
            T: 60
            lr : 0.035
            lambd: 1.99
    testing_louvain:
      tau_0.5:
        beta_0.5:
            T: 20
            lr : 0.0053
            lambd: 0.81
        beta_1:
            T: 60
            lr : 0.054
            lambd: 0.81
        beta_2:
            T: 30
            lr : 0.039
            lambd: 0.77
    testing_walktrap:
      tau_0.5:
        beta_0.5:
            T: 90
            lr : 0.071
            lambd: 0.36
        beta_1:
            T: 90
            lr : 0.086
            lambd: 0.02
        beta_2:
            T: 60
            lr : 0.096
            lambd: 0.003

vote:
  evader:
    T: 100
    u: 10
    lambd: 10
    lr: 0.005
    dist_f: frobenius_dist
    budget_factor: 1
    tau: 0.5
    attention: True
    reinitialization: True

